/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;
import objects.AgendamentoAnimal;
import connections.MySQL;
import javax.swing.JOptionPane;

/**
 *
 * @author annas
 */
public class newAgendamento extends javax.swing.JFrame {
        MySQL conectar = new MySQL();
        AgendamentoAnimal novoAgendamento = new AgendamentoAnimal();
    /**
     * Creates new form agendamento
     */
    public newAgendamento() {
        initComponents();
    }
    private void cadNovoAgendamento(AgendamentoAnimal novoAgendamento){
    this.conectar.conectaBanco();
    novoAgendamento.setAnimal((String)cmb_animal.getSelectedItem());
    novoAgendamento.setNomeAnimal(txt_nome_animal.getText());
    novoAgendamento.setNomeDono(txt_nome_dono.getText());
    novoAgendamento.setTelefone(txt_telefone.getText());
    novoAgendamento.setDia((String)cmb_dia.getSelectedItem());
    novoAgendamento.setServico((String)cmb_servico.getSelectedItem());
    
    //String Animal;String nomeDono;String telefone;String dia;String servico;
    
    try{
    this.conectar.insertSQL("INSERT INTO agendamento("
    + "animal,"
    + "nomeAnimal,"
    + "nomeDono,"
    + "telefone,"
    + "dia,"
    + "servico"
    + ")VALUES("
    + "'" +novoAgendamento.getAnimal()+"',"
    + "'" +novoAgendamento.getNomeAnimal()+ "',"
    + "'" +novoAgendamento.getNomeDono()+ "',"
    + "'" +novoAgendamento.getTelefone()+"',"
    + "'" +novoAgendamento.getDia()+ "',"
    + "'" +novoAgendamento.getServico()+"'"
    + ");");
     } catch (Exception e){
            System.err.println("Erro ao cadastrar Usuario" + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar Usuario");
        } finally{
            this.conectar.fechaBanco();
            JOptionPane.showMessageDialog(null, "Usuario cadastrado com sucesso");
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_agenda = new javax.swing.JButton();
        btn_agendamento = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_agendar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_nome_dono = new javax.swing.JTextField();
        txt_telefone = new javax.swing.JTextField();
        lbl_aviso = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmb_animal = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txt_nome_animal = new javax.swing.JTextField();
        cmb_dia = new javax.swing.JComboBox<>();
        cmb_servico = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(767, 540));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(240, 140, 23));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BEM VINDO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 70, 220, 30);

        btn_agenda.setBackground(new java.awt.Color(231, 168, 95));
        btn_agenda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_agenda.setForeground(new java.awt.Color(255, 255, 255));
        btn_agenda.setText("AGENDA");
        btn_agenda.setBorder(null);
        btn_agenda.setRequestFocusEnabled(false);
        btn_agenda.setRolloverEnabled(false);
        btn_agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agendaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agenda);
        btn_agenda.setBounds(0, 190, 220, 48);

        btn_agendamento.setBackground(new java.awt.Color(231, 168, 95));
        btn_agendamento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_agendamento.setForeground(new java.awt.Color(255, 255, 255));
        btn_agendamento.setText("AGENDAMENTO");
        btn_agendamento.setBorder(null);
        btn_agendamento.setBorderPainted(false);
        btn_agendamento.setFocusPainted(false);
        btn_agendamento.setFocusable(false);
        btn_agendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agendamentoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agendamento);
        btn_agendamento.setBounds(0, 140, 220, 48);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 220, 540);

        jPanel2.setBackground(new java.awt.Color(0, 63, 89));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Telefone");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(90, 230, 61, 20);

        btn_agendar.setBackground(new java.awt.Color(240, 140, 23));
        btn_agendar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_agendar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agendar.setText("Agendar");
        btn_agendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agendarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_agendar);
        btn_agendar.setBounds(190, 440, 150, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Serviço");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(90, 350, 61, 20);
        jPanel2.add(txt_nome_dono);
        txt_nome_dono.setBounds(90, 190, 380, 30);
        jPanel2.add(txt_telefone);
        txt_telefone.setBounds(90, 250, 380, 30);

        lbl_aviso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_aviso.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lbl_aviso);
        lbl_aviso.setBounds(90, 410, 380, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Animal");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(90, 50, 61, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nome Dono");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(90, 170, 100, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dia");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(90, 290, 61, 20);

        cmb_animal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gato", "Cachorro" }));
        cmb_animal.setFocusable(false);
        cmb_animal.setLightWeightPopupEnabled(false);
        cmb_animal.setRequestFocusEnabled(false);
        cmb_animal.setVerifyInputWhenFocusTarget(false);
        cmb_animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_animalActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_animal);
        cmb_animal.setBounds(90, 70, 380, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nome Animal");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(90, 110, 100, 20);
        jPanel2.add(txt_nome_animal);
        txt_nome_animal.setBounds(90, 130, 380, 30);

        cmb_dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Segunda", "Terca", "Quarta", "Quinta", "Sexta", "Sabado" }));
        cmb_dia.setFocusable(false);
        cmb_dia.setLightWeightPopupEnabled(false);
        cmb_dia.setRequestFocusEnabled(false);
        cmb_dia.setVerifyInputWhenFocusTarget(false);
        cmb_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_diaActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_dia);
        cmb_dia.setBounds(90, 310, 380, 30);

        cmb_servico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banho", "Tosa", "Banho & Tosa" }));
        cmb_servico.setFocusable(false);
        cmb_servico.setLightWeightPopupEnabled(false);
        cmb_servico.setRequestFocusEnabled(false);
        cmb_servico.setVerifyInputWhenFocusTarget(false);
        cmb_servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_servicoActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_servico);
        cmb_servico.setBounds(90, 370, 380, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(220, 0, 550, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agendaActionPerformed
        agenda agend = new agenda();
        agend.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_agendaActionPerformed

    private void btn_agendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agendamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agendamentoActionPerformed
    
    private void btn_agendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agendarActionPerformed
        cadNovoAgendamento(novoAgendamento);
    }//GEN-LAST:event_btn_agendarActionPerformed

    private void cmb_servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_servicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_servicoActionPerformed

    private void cmb_animalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_animalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_animalActionPerformed

    private void cmb_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_diaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newAgendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agenda;
    private javax.swing.JButton btn_agendamento;
    private javax.swing.JButton btn_agendar;
    private javax.swing.JComboBox<String> cmb_animal;
    private javax.swing.JComboBox<String> cmb_dia;
    private javax.swing.JComboBox<String> cmb_servico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_aviso;
    private javax.swing.JTextField txt_nome_animal;
    private javax.swing.JTextField txt_nome_dono;
    private javax.swing.JTextField txt_telefone;
    // End of variables declaration//GEN-END:variables

    
}
