/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;


/**
 *
 * @author annas
 */
public class newAccount extends javax.swing.JFrame {

    /**
     * Creates new form newAccount
     */
    public newAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_user = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_senha = new javax.swing.JTextField();
        txt_senhadois = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btn_criar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_aviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 63, 89));

        jPanel2.setBackground(new java.awt.Color(249, 249, 249));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMaximumSize(new java.awt.Dimension(473, 509));
        jPanel2.setMinimumSize(new java.awt.Dimension(473, 509));
        jPanel2.setLayout(null);

        txt_user.setForeground(new java.awt.Color(14, 14, 14));
        txt_user.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(140, 140, 140), 1, true));
        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });
        jPanel2.add(txt_user);
        txt_user.setBounds(80, 190, 350, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Senha:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(80, 240, 37, 16);

        txt_senha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(140, 140, 140), 1, true));
        jPanel2.add(txt_senha);
        txt_senha.setBounds(80, 260, 350, 25);

        txt_senhadois.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(140, 140, 140), 1, true));
        jPanel2.add(txt_senhadois);
        txt_senhadois.setBounds(80, 330, 350, 25);

        btn_login.setBackground(new java.awt.Color(0, 63, 89));
        btn_login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Já tenho uma conta");
        btn_login.setBorder(null);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel2.add(btn_login);
        btn_login.setBounds(160, 440, 190, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconDog.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(230, 30, 60, 60);

        btn_criar.setBackground(new java.awt.Color(240, 140, 23));
        btn_criar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_criar.setForeground(new java.awt.Color(255, 255, 255));
        btn_criar.setText("Criar");
        btn_criar.setBorder(null);
        btn_criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_criarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_criar);
        btn_criar.setBounds(200, 390, 120, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("E-mail:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 170, 50, 16);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Confirme a senha");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(80, 310, 150, 16);
        jPanel2.add(lbl_aviso);
        lbl_aviso.setBounds(80, 360, 350, 20);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        login logar = new login();
        
        logar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userActionPerformed
    
    private void setLabel(String texto, Color cor){
        lbl_aviso.setText(texto);
        lbl_aviso.setForeground(cor);
    }
    
    private Boolean senhasIguais(String senhaUm, String senhaDois){
      
        if(senhaUm.equals(senhaDois)){
                return true;
            }
        return false;
    }
    private void btn_criarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_criarActionPerformed
        String user = txt_user.getText();
        String senha = txt_senha.getText();
        String senhadois = txt_senhadois.getText();
        
        if(!senha.equals("") && !senhadois.equals("") && !user.equals("")){
            Boolean senhasValida = senhasIguais(senha,senhadois);
                if(senhasValida == true){
                setLabel("",Color.white);
                //toda logica de cadastro no mysql
               }else{
                setLabel("Senhas incompativeis", Color.black);
            } 
        }else{
            setLabel("Preencha os campos", Color.red);
        }
        
        
        
    }//GEN-LAST:event_btn_criarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_criar;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_aviso;
    private javax.swing.JTextField txt_senha;
    private javax.swing.JTextField txt_senhadois;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
